services:
  - type: web
    name: whatsapp-financial-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: TWILIO_ACCOUNT_SID
        value: ${TWILIO_ACCOUNT_SID}
      - key: TWILIO_AUTH_TOKEN
        value: ${TWILIO_AUTH_TOKEN}
      - key: TWILIO_PHONE_NUMBER
        value: ${TWILIO_PHONE_NUMBER}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: PYTHON_VERSION
      

databases:
  - name: whatsapp-financial-tracker-db
    databaseName: whatsapp_financial_tracker
    user: whatsapp_financial_tracker_user
